### ISSUE TITLE
Update pre-commit checks

### ISSUE THREAD

**Issue by JafarAbdi** [PickNikRobotics/ros2_package_template#7]
https://github.com/PickNikRobotics/pick_ik/blob/main/.pre-commit-config.yaml

```yaml
repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        args: ['--unsafe']  # Fixes errors parsing custom YAML constructors like ur_description's !degrees
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: fix-byte-order-marker

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
      - id: codespell
        args: ['--write-changes', '-L', 'atleast,inout']  # Provide a comma-separated list of misspelled words that codespell should ignore (for example: '-L', 'word1,word2,word3').
        exclude: \.(svg|pyc|stl|dae|lock)$

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
        files: \.(c|cc|cxx|cpp|frag|glsl|h|hpp|hxx|ih|ispc|ipp|java|m|proto|vert)$
        # -i arg is included by default by the hook
        args: ['-fallback-style=none']

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.27.1
    hooks:
      - id: yamllint
        args: ["--no-warnings", "--config-data", "{extends: default, rules: {line-length: disable}}"]
        types: [text]
        files: (moveit_studio.repos|docker-compose.yaml)

  # NOTE: Broken on arm64. Will need to bump once https://github.com/hadolint/hadolint/issues/840 is fixed.
  - repo: https://github.com/hadolint/hadolint
    rev: v2.10.0
    hooks:
      - id: hadolint-docker
```
